# **Assignment For Numpy**

Difficulty Level **Beginner**

1. Import the numpy package under the name np

In [1]:
import numpy as np

2. Create a null vector of size 10 

In [2]:
arr1 = np.zeros(10)
print(arr1)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


3. Create a vector with values ranging from 10 to 49

In [3]:
arr2 = np.linspace(10,49)
print(arr2)

[10.         10.79591837 11.59183673 12.3877551  13.18367347 13.97959184
 14.7755102  15.57142857 16.36734694 17.16326531 17.95918367 18.75510204
 19.55102041 20.34693878 21.14285714 21.93877551 22.73469388 23.53061224
 24.32653061 25.12244898 25.91836735 26.71428571 27.51020408 28.30612245
 29.10204082 29.89795918 30.69387755 31.48979592 32.28571429 33.08163265
 33.87755102 34.67346939 35.46938776 36.26530612 37.06122449 37.85714286
 38.65306122 39.44897959 40.24489796 41.04081633 41.83673469 42.63265306
 43.42857143 44.2244898  45.02040816 45.81632653 46.6122449  47.40816327
 48.20408163 49.        ]


4. Find the shape of previous array in question 3

In [4]:
arr2.shape

(50,)

5. Print the type of the previous array in question 3

In [5]:
type(arr2)

numpy.ndarray

6. Print the numpy version and the configuration


In [6]:
print(np.__version__)
print(np.show_config())

1.19.0
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_info']
    libraries = ['openblas_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_info']
    libraries = ['openblas_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_lapack_info']
    libraries = ['openblas_lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_lapack_info']
    libraries = ['openblas_lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
None


7. Print the dimension of the array in question 3


In [7]:
print(arr2.ndim)

1


8. Create a boolean array with all the True values

In [8]:
arr3 = np.ones((10), dtype=bool)
print(arr3)

[ True  True  True  True  True  True  True  True  True  True]


9. Create a two dimensional array




In [9]:
arr4 = np.array([[2, 4, 6], [6, 8, 10]], np.int32)
arr4.ndim

2

10. Create a three dimensional array



In [10]:
arr5 = np.array([[[2, 4, 6], [6, 8, 10],[2,2,2]]], np.int32)
arr5.ndim

3

Difficulty Level **Easy**

11. Reverse a vector (first element becomes last)

In [11]:
arr2_rev = arr2[::-1]
arr2_rev

array([49.        , 48.20408163, 47.40816327, 46.6122449 , 45.81632653,
       45.02040816, 44.2244898 , 43.42857143, 42.63265306, 41.83673469,
       41.04081633, 40.24489796, 39.44897959, 38.65306122, 37.85714286,
       37.06122449, 36.26530612, 35.46938776, 34.67346939, 33.87755102,
       33.08163265, 32.28571429, 31.48979592, 30.69387755, 29.89795918,
       29.10204082, 28.30612245, 27.51020408, 26.71428571, 25.91836735,
       25.12244898, 24.32653061, 23.53061224, 22.73469388, 21.93877551,
       21.14285714, 20.34693878, 19.55102041, 18.75510204, 17.95918367,
       17.16326531, 16.36734694, 15.57142857, 14.7755102 , 13.97959184,
       13.18367347, 12.3877551 , 11.59183673, 10.79591837, 10.        ])

12. Create a null vector of size 10 but the fifth value which is 1 

In [12]:
null = np.zeros(10)
null[5] = 1
null

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.])

13. Create a 3x3 identity matrix

In [13]:
identity = np.identity(3)
identity

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

14. arr = np.array([1, 2, 3, 4, 5]) 

---

 Convert the data type of the given array from int to float 

In [14]:
arr = np.array([1, 2, 3, 4, 5],dtype=float)
arr

array([1., 2., 3., 4., 5.])

15. arr1 =          np.array([[1., 2., 3.],

                    [4., 5., 6.]])  
                      
    arr2 = np.array([[0., 4., 1.],
     
                   [7., 2., 12.]])

---


Multiply arr1 with arr2


In [15]:
arr1 = np.array([[1., 2., 3.],

            [4., 5., 6.]])

arr2 = np.array([[0., 4., 1.],

           [7., 2., 12.]])

print(arr1*arr2)

[[ 0.  8.  3.]
 [28. 10. 72.]]


16. arr1 = np.array([[1., 2., 3.],
                    [4., 5., 6.]]) 
                    
    arr2 = np.array([[0., 4., 1.], 
                    [7., 2., 12.]])


---

Make an array by comparing both the arrays provided above

In [16]:
arr1 = np.array([[1., 2., 3.],

            [4., 5., 6.]]) 
arr2 = np.array([[0., 4., 1.],

            [7., 2., 12.]])

arr1 == arr2

array([[False, False, False],
       [False, False, False]])

17. Extract all odd numbers from arr with values(0-9)

In [17]:
arr = np.array([1, 2, 3, 4, 5])
answer = arr[arr%2==1]
answer

array([1, 3, 5])

18. Replace all odd numbers to -1 from previous array

In [18]:
arr = np.array([1, 2, 3, 4, 5])
arr[arr%2==1] = -1
arr

array([-1,  2, -1,  4, -1])

19. arr = np.arange(10)


---

Replace the values of indexes 5,6,7 and 8 to **12**

In [19]:
arr = np.arange(10)
arr[[5,6,7,8]] = 12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12, 12,  9])

20. Create a 2d array with 1 on the border and 0 inside

In [20]:
x = np.ones((5,5))
print(x)
x[1:-1,1:-1] = 0
x

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

Difficulty Level **Medium**

21. arr2d = np.array([[1, 2, 3],

                    [4, 5, 6], 

                    [7, 8, 9]])

---

Replace the value 5 to 12

In [21]:
arr2d = np.array([[1, 2, 3],

            [4, 5, 6], 

            [7, 8, 9]])

arr2d[1][1]=12
arr2d

array([[ 1,  2,  3],
       [ 4, 12,  6],
       [ 7,  8,  9]])

22. arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

---
Convert all the values of 1st array to 64


In [22]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d[0,:,:] = 1
arr3d

array([[[ 1,  1,  1],
        [ 1,  1,  1]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

23. Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it

In [23]:
array2d = np.random.randint(10, size=(3,3))
print(array2d)
print('after slicing')
print(array2d[:1,:])

[[8 9 2]
 [3 4 4]
 [0 9 6]]
after slicing
[[8 9 2]]


24. Make a 2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it

In [24]:
array2d = np.random.randint(10, size=(3,3))
print(array2d)
print('after slicing')
print(array2d[1:2,1:2])

[[1 5 2]
 [4 9 6]
 [2 5 1]]
after slicing
[[9]]


25. Make a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows

In [25]:
array2d = np.random.randint(10, size=(3,3))
print(array2d)
print('after slicing')
print(array2d[:2,2:3])

[[3 5 7]
 [5 5 3]
 [6 3 2]]
after slicing
[[7]
 [3]]


26. Create a 10x10 array with random values and find the minimum and maximum values

In [26]:
array2d = np.random.randn(10,10)
print(np.max(array2d))
print(np.min(array2d))

2.486896313312993
-2.3839401952182944


27. a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])
---
Find the common items between a and b


In [27]:
a = np.array([1,2,3,2,3,4,3,4,5,6]) 
b = np.array([7,2,10,2,7,4,9,4,9,8])
print(np.intersect1d(a, b))

[2 4]


28. a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

---
Find the positions where elements of a and b match



In [28]:
a = np.array([1,2,3,2,3,4,3,4,5,6]) 
b = np.array([7,2,10,2,7,4,9,4,9,8])
print(np.where(a == b))

(array([1, 3, 5, 7], dtype=int32),)


29.  names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])  data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will**


In [29]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 
data = np.random.randn(7, 4)
print(data[names!='Will'])


[[-1.12565008 -1.87593254  0.0744415   0.95257764]
 [ 0.28763661  1.50673472 -0.76448829  0.80230739]
 [ 0.51809187 -0.52404953 -1.88809882  0.46230306]
 [ 0.25932123 -1.06346818 -1.62585294  0.67542587]
 [-2.87117738  0.63902914  0.3947066  -0.1680289 ]]


30. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will** and **Joe**



In [30]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 
data = np.random.randn(7, 4)
data[(names!='Will') * (names!='Joe')]

array([[-0.53837444,  2.71113471, -0.62706846, -0.6292435 ],
       [ 0.70372479, -0.6583445 , -0.17792373,  0.47297823]])

Difficulty Level **Hard**

31. Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15.

In [31]:
array2d = np.random.randint(1,15, size=(5,3))
array2d

array([[11,  2,  6],
       [ 5, 11, 13],
       [10,  3,  8],
       [ 9,  2,  4],
       [ 4,  8,  4]])

32. Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16.

In [32]:
a= np.random.randint(1,16, size=(2,2,4))
a

array([[[ 7,  9, 14, 13],
        [ 5, 11,  7, 12]],

       [[12, 15,  8, 15],
        [12, 10,  8, 15]]])

33. Swap axes of the array you created in Question 32

In [33]:
a.T

array([[[ 7, 12],
        [ 5, 12]],

       [[ 9, 15],
        [11, 10]],

       [[14,  8],
        [ 7,  8]],

       [[13, 15],
        [12, 15]]])

34. Create an array of size 10, and find the square root of every element in the array, if the values less than 0.5, replace them with 0

In [34]:
arr = np.arange(10)
arr = np.sqrt(arr)
arr[arr<0.5] = 0
arr

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

35. Create two random arrays of range 12 and make an array with the maximum values between each element of the two arrays

In [35]:
x = np.random.randn(12)
y = np.random.randn(12)
np.maximum(x,y)

array([ 2.15983112,  0.33560386, -0.71082604,  0.54493882,  1.2895405 ,
        0.41260645, -0.84195944,  1.23680104, -1.16666664,  0.17401763,
        1.47373043,  2.02013205])

36. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

---
Find the unique names and sort them out!


In [36]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
np.sort(np.unique(names))


array(['Bob', 'Joe', 'Will'], dtype='<U4')

37. a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

---
From array a remove all items present in array b



In [37]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
result = np.setdiff1d(a, b)
print(result)

[1 2 3 4]


38.  Following is the input NumPy array delete column two and insert following new column in its place.

---
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]]) 


---

newColumn = numpy.array([[10,10,10]])


In [38]:
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]])
newColumn = np.array([[10,10,10]])
sampleArray=np.delete(sampleArray, 1, 1)
print(np.insert(sampleArray, 1,newColumn , axis=1))

[[34 10 73]
 [82 10 12]
 [53 10 66]]


39. x = np.array([[1., 2., 3.], [4., 5., 6.]]) y = np.array([[6., 23.], [-1, 7], [8, 9]])


---
Find the dot product of the above two matrix


In [39]:
x = np.array([[1., 2., 3.], [4., 5., 6.]])
y = np.array([[6., 23.], [-1, 7], [8, 9]])
np.dot(x,y)

array([[ 28.,  64.],
       [ 67., 181.]])

40. Generate a matrix of 20 random values and find its cumulative sum

In [40]:
a=np.random.randn(20)
np.cumsum(a)

array([-0.52501098, -1.52610208, -0.50650907, -0.08578076,  0.25624649,
       -1.18798534, -2.17020712, -2.79192321, -2.44294524, -2.89376085,
       -3.0442625 , -2.63390461, -1.88973966, -1.31802091, -1.49356511,
       -1.64368788, -2.6724362 , -4.79046582, -5.01589284, -6.79655338])